# Reduce Data Set
The original data set had over 51 million rows, so we opted to reduce it by using only the last 6 years (2012-2017) and flattening the rows to contain data for each day as opposed to each hour.

In [1]:
import pandas as pd
import numpy as np

dlst = pd.read_stata("../spring forward/data/stats19/final/final.dta")

In [17]:
len(dlst)

51103130

In [2]:
dlst.head()

mlong   mlat       date  hour  all_accid  u25_accid  o25u45_accid  \
0  -7.75  56.75 1996-01-01     0          0          0             0   
1  -7.75  56.75 1996-01-01     1          0          0             0   
2  -7.75  56.75 1996-01-01     2          0          0             0   
3  -7.75  56.75 1996-01-01     3          0          0             0   
4  -7.75  56.75 1996-01-01     4          0          0             0   

   o45u65_accid  o65_accid  ped_accid  ...  slight_accid       sunrise6_time  \
0             0          0          0  ...             0 1960-01-01 08:19:00   
1             0          0          0  ...             0 1960-01-01 08:19:00   
2             0          0          0  ...             0 1960-01-01 08:19:00   
3             0          0          0  ...             0 1960-01-01 08:19:00   
4             0          0          0  ...             0 1960-01-01 08:19:00   

         sunset6_time  samplew  year doy dow  longlat  dark  darkh  
0 1960-01-01 16:49:00        0  1996   1   2       15   1.0   15.5  
1 1960-01-01 16:49:00        0  1996   1   2       15   1.0   15.5  
2 1960-01-01 16:49:00        0  1996   1   2       15   1.0   15.5  
3 1960-01-01 16:49:00        0  1996   1   2       15   1.0   15.5  
4 1960-01-01 16:49:00        0  1996   1   2       15   1.0   15.5  

[5 rows x 24 columns]

In [5]:
print(dlst.columns)

Index(['mlong', 'mlat', 'date', 'hour', 'all_accid', 'u25_accid',
       'o25u45_accid', 'o45u65_accid', 'o65_accid', 'ped_accid',
       'ped_u45_accid', 'ped_o45_accid', 'fat_accid', 'ser_accid',
       'slight_accid', 'sunrise6_time', 'sunset6_time', 'samplew', 'year',
       'doy', 'dow', 'longlat', 'dark', 'darkh'],
      dtype='object')


In [6]:
dlst["samplew"].unique()

array([0, 1], dtype=int8)

In [8]:
dlst2 = dlst[dlst["year"] >= 2012]

In [11]:
dlst3 = dlst2.groupby(by=["mlong", "mlat", "date", "sunrise6_time", "sunset6_time", "year", "doy", "dow", "longlat", "darkh"], as_index=False).agg(
    {'all_accid': "sum",
     'u25_accid': "sum",
     'o25u45_accid': "sum",
     'o45u65_accid': "sum",
     'o65_accid': "sum",
     'ped_accid': "sum",
     'ped_u45_accid': "sum",
     'ped_o45_accid': "sum",
     'fat_accid': "sum",
     'ser_accid': "sum",
     'slight_accid': "sum"}
)

In [12]:
dlst3

mlong   mlat       date       sunrise6_time        sunset6_time  year  \
0       -7.75  56.75 2012-01-01 1960-01-01 08:19:00 1960-01-01 16:49:00  2012   
1       -7.75  56.75 2012-01-02 1960-01-01 08:18:00 1960-01-01 16:50:00  2012   
2       -7.75  56.75 2012-01-03 1960-01-01 08:18:00 1960-01-01 16:52:00  2012   
3       -7.75  56.75 2012-01-04 1960-01-01 08:18:00 1960-01-01 16:53:00  2012   
4       -7.75  56.75 2012-01-05 1960-01-01 08:18:00 1960-01-01 16:54:00  2012   
...       ...    ...        ...                 ...                 ...   ...   
908949   1.75  55.25 2017-12-27 1960-01-01 07:33:00 1960-01-01 16:14:00  2017   
908950   1.75  55.25 2017-12-28 1960-01-01 07:33:00 1960-01-01 16:15:00  2017   
908951   1.75  55.25 2017-12-29 1960-01-01 07:33:00 1960-01-01 16:16:00  2017   
908952   1.75  55.25 2017-12-30 1960-01-01 07:34:00 1960-01-01 16:17:00  2017   
908953   1.75  55.25 2017-12-31 1960-01-01 07:34:00 1960-01-01 16:18:00  2017   

        doy  dow  longlat      darkh  ...  u25_accid  o25u45_accid  \
0         1    1       15  15.500000  ...          0             0   
1         2    2       15  15.466666  ...          0             0   
2         3    3       15  15.433333  ...          0             0   
3         4    4       15  15.416667  ...          0             0   
4         5    5       15  15.400000  ...          0             0   
...     ...  ...      ...        ...  ...        ...           ...   
908949  362    4      449  15.316667  ...          0             0   
908950  363    5      449  15.300000  ...          0             0   
908951  364    6      449  15.283334  ...          0             0   
908952  365    7      449  15.283333  ...          0             0   
908953  366    1      449  15.266666  ...          0             0   

        o45u65_accid  o65_accid  ped_accid  ped_u45_accid  ped_o45_accid  \
0                  0          0          0              0              0   
1                  0          0          0              0              0   
2                  0          0          0              0              0   
3                  0          0          0              0              0   
4                  0          0          0              0              0   
...              ...        ...        ...            ...            ...   
908949             0          0          0              0              0   
908950             0          0          0              0              0   
908951             0          0          0              0              0   
908952             0          0          0              0              0   
908953             0          0          0              0              0   

        fat_accid  ser_accid  slight_accid  
0               0          0             0  
1               0          0             0  
2               0          0             0  
3               0          0             0  
4               0          0             0  
...           ...        ...           ...  
908949          0          0             0  
908950          0          0             0  
908951          0          0             0  
908952          0          0             0  
908953          0          0             0  

[908954 rows x 21 columns]

In [13]:
dlst3["all_accid"].unique()

array([ 0,  1,  2,  3,  5,  4,  8,  6,  9,  7, 12, 11, 16, 14, 13, 10, 15,
       17, 18, 19, 21, 20, 26, 22, 25, 24, 23, 27, 28, 30, 29, 33, 36, 38,
       32, 31, 35, 45, 41, 34, 37, 39, 44, 48, 46, 47, 42, 40, 49, 43, 51,
       50, 53, 52, 64, 56, 55, 58, 59, 54, 60, 57, 62, 61, 66, 68, 74, 69,
       63, 65, 75, 71, 73, 70, 77], dtype=int8)

In [14]:
dlst3["fat_accid"].unique()

array([0, 1, 2, 3], dtype=int8)

In [15]:
dlst3[dlst3["all_accid"] > 60]

mlong   mlat       date       sunrise6_time        sunset6_time  year  \
773505  -0.25  51.25 2014-10-09 1960-01-01 06:41:00 1960-01-01 18:54:00  2014   
775634  -0.25  51.75 2012-07-24 1960-01-01 04:29:00 1960-01-01 21:44:00  2012   
775780  -0.25  51.75 2012-10-05 1960-01-01 06:35:00 1960-01-01 19:02:00  2012   
776184  -0.25  51.75 2013-07-15 1960-01-01 04:15:00 1960-01-01 21:57:00  2013   
776404  -0.25  51.75 2013-11-08 1960-01-01 06:31:00 1960-01-01 16:57:00  2013   
776407  -0.25  51.75 2013-11-11 1960-01-01 06:36:00 1960-01-01 16:53:00  2013   
776443  -0.25  51.75 2013-12-17 1960-01-01 07:22:00 1960-01-01 16:31:00  2013   
776486  -0.25  51.75 2014-01-29 1960-01-01 07:07:00 1960-01-01 17:20:00  2014   
776653  -0.25  51.75 2014-05-23 1960-01-01 04:13:00 1960-01-01 21:42:00  2014   
776688  -0.25  51.75 2014-06-10 1960-01-01 03:55:00 1960-01-01 22:05:00  2014   
776695  -0.25  51.75 2014-06-13 1960-01-01 03:54:00 1960-01-01 22:08:00  2014   
776701  -0.25  51.75 2014-06-17 1960-01-01 03:53:00 1960-01-01 22:10:00  2014   
776715  -0.25  51.75 2014-06-27 1960-01-01 03:56:00 1960-01-01 22:11:00  2014   
776725  -0.25  51.75 2014-07-03 1960-01-01 04:00:00 1960-01-01 22:09:00  2014   
776767  -0.25  51.75 2014-07-24 1960-01-01 04:28:00 1960-01-01 21:45:00  2014   
776907  -0.25  51.75 2014-10-02 1960-01-01 06:29:00 1960-01-01 19:09:00  2014   
776963  -0.25  51.75 2014-11-03 1960-01-01 06:22:00 1960-01-01 17:05:00  2014   
776964  -0.25  51.75 2014-11-04 1960-01-01 06:24:00 1960-01-01 17:03:00  2014   
776968  -0.25  51.75 2014-11-08 1960-01-01 06:31:00 1960-01-01 16:57:00  2014   
776972  -0.25  51.75 2014-11-12 1960-01-01 06:37:00 1960-01-01 16:51:00  2014   
776985  -0.25  51.75 2014-11-25 1960-01-01 06:57:00 1960-01-01 16:37:00  2014   
777084  -0.25  51.75 2015-03-04 1960-01-01 06:07:00 1960-01-01 18:19:00  2015   
777257  -0.25  51.75 2015-06-11 1960-01-01 03:55:00 1960-01-01 22:06:00  2015   
777276  -0.25  51.75 2015-06-24 1960-01-01 03:54:00 1960-01-01 22:11:00  2015   
777285  -0.25  51.75 2015-06-30 1960-01-01 03:57:00 1960-01-01 22:10:00  2015   
777360  -0.25  51.75 2015-08-06 1960-01-01 04:50:00 1960-01-01 21:21:00  2015   
777432  -0.25  51.75 2015-09-11 1960-01-01 05:54:00 1960-01-01 19:59:00  2015   
777452  -0.25  51.75 2015-09-21 1960-01-01 06:11:00 1960-01-01 19:36:00  2015   
777531  -0.25  51.75 2015-11-05 1960-01-01 06:25:00 1960-01-01 17:02:00  2015   
777539  -0.25  51.75 2015-11-13 1960-01-01 06:38:00 1960-01-01 16:50:00  2015   
777553  -0.25  51.75 2015-11-27 1960-01-01 07:00:00 1960-01-01 16:36:00  2015   
777565  -0.25  51.75 2015-12-09 1960-01-01 07:15:00 1960-01-01 16:31:00  2015   
777571  -0.25  51.75 2015-12-15 1960-01-01 07:20:00 1960-01-01 16:31:00  2015   
777844  -0.25  51.75 2016-06-24 1960-01-01 03:54:00 1960-01-01 22:11:00  2016   
777867  -0.25  51.75 2016-07-06 1960-01-01 04:04:00 1960-01-01 22:06:00  2016   
777891  -0.25  51.75 2016-07-18 1960-01-01 04:20:00 1960-01-01 21:53:00  2016   
778103  -0.25  51.75 2016-11-03 1960-01-01 06:23:00 1960-01-01 17:04:00  2016   
778104  -0.25  51.75 2016-11-04 1960-01-01 06:25:00 1960-01-01 17:03:00  2016   
778111  -0.25  51.75 2016-11-11 1960-01-01 06:36:00 1960-01-01 16:52:00  2016   
778116  -0.25  51.75 2016-11-16 1960-01-01 06:44:00 1960-01-01 16:46:00  2016   
778118  -0.25  51.75 2016-11-18 1960-01-01 06:47:00 1960-01-01 16:44:00  2016   
778125  -0.25  51.75 2016-11-25 1960-01-01 06:58:00 1960-01-01 16:37:00  2016   
778132  -0.25  51.75 2016-12-02 1960-01-01 07:07:00 1960-01-01 16:33:00  2016   
778137  -0.25  51.75 2016-12-07 1960-01-01 07:13:00 1960-01-01 16:31:00  2016   
778140  -0.25  51.75 2016-12-10 1960-01-01 07:16:00 1960-01-01 16:31:00  2016   
778170  -0.25  51.75 2017-01-09 1960-01-01 07:25:00 1960-01-01 16:51:00  2017   
778255  -0.25  51.75 2017-03-31 1960-01-01 06:04:00 1960-01-01 20:07:00  2017   
778404  -0.25  51.75 2017-06-14 1960-01-01 03:54:00 1960-01-01 22:08:00  2017   
778436  -0.25  51.75 2017-07-04 1960-01

In [16]:
dlst3.to_csv("dlst_red.csv", index=False)